apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello-arc
  namespace: prod
spec:
  releaseName: hello-arc-prod
  chart:
    git: https://github.com/irisfang2018/hello_arc.git
    path: charts/hello-arc
    ref: master
  values:
    image:
      repository: liorkamrat/hello-arc
      tag: latest
    replicaCount: 1
    env:
      name: MESSAGE
      value: Welcome to MTC Silicon Valley. This is Arc GitOps Demo Message from Production.
